site_name: My Docs
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.indexes
plugins:
- search
repo_url: https://github.com/openshift/hypershift
repo_name: openshift/hypershift
markdown_extensions:
- toc:
    toc_depth: "2-3"
