site_name: My Docs
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.indexes
plugins:
- search
repo_url: https://github.com/feven-redhat/homelab
repo_name: feven-redhat/homelab
docs_dir: content
markdown_extensions:
- toc:
    toc_depth: "2-3"
