site_name: My Docs
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.indexes
  - content.code.annotate
plugins:
- search
docs_dir: content
repo_url: https://github.com/openshift/hypershift
edit_uri: edit/main/docs/content
repo_name: openshift/hypershift
markdown_extensions:
- toc:
    toc_depth: "2-3"
